# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.6
_src_path: gh:ceesem/cave-copier
directory_name: datafolio
github_user: ceesem
initial_version: 0.0.1
project_description: Lightweight wrapping of dataframes, models, and metadata to track analyses.
project_name: DataFolio
project_slug: datafolio
python_version: '3.12'
template_type: library
use_vim_jupyter: true
user_email: caseysm@gmail.com
user_name: Casey Schneider-Mizell
